ARDMK_DIR     		= /usr/share/arduino
MONITOR_PORT  		= /dev/ttyUSB0
BOARD_TAG     		= nano328
CXXFLAGS        	= -Os
CFLAGS			= -Os -w
ARDUINO_LIBS		= lsm303-arduino Wire
ARDUINO_SKETCHBOOK	= .
include /usr/share/arduino/Arduino.mk
